# Generated by Django 6.0.3 on 2026-03-14 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус операции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание операции')),
            ],
            options={
                'verbose_name': 'Запрос на транскрибацию',
                'verbose_name_plural': 'Запросы на транскрибацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=100, verbose_name='Спикер')),
                ('text', models.TextField(verbose_name='Текст фразы')),
                ('start_time', models.FloatField(verbose_name='Начальное время (секунды)')),
                ('end_time', models.FloatField(verbose_name='Конечное время (секунды)')),
                ('transcription_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='main.transcriptionrequest', verbose_name='Запрос на транскрибацию')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
                'ordering': ['start_time'],
            },
        ),
    ]
