# Generated by Django 5.2.8 on 2026-03-25 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_routeaccess_transcription_result_delete_phrase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='main.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к файлу',
                'verbose_name_plural': 'Доступы к файлам',
                'db_table': 'file_access',
                'unique_together': {('file', 'user')},
            },
        ),
    ]
