# Generated by Django 5.2.8 on 2026-03-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fileaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccess',
            name='action',
            field=models.CharField(choices=[('r', 'Read - только просмотр'), ('w', 'Write - просмотр и редактирование')], default='r', max_length=1),
        ),
    ]
