# Generated by Django 5.2.7 on 2026-04-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fileaccess_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileaccess',
            name='action',
        ),
        migrations.AddField(
            model_name='fileaccess',
            name='permission',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование')], default='view', max_length=10),
        ),
        migrations.AddField(
            model_name='transcription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='name',
            field=models.CharField(default='Без названия', max_length=255),
        ),
        migrations.AlterModelTable(
            name='fileaccess',
            table=None,
        ),
    ]
