# Generated by Django 5.2.8 on 2026-04-22 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_fileaccess_action_fileaccess_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_text', models.TextField()),
                ('compressed_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='main.transcription')),
            ],
            options={
                'verbose_name': 'Протокол встречи',
                'verbose_name_plural': 'Протоколы встреч',
                'ordering': ['-created_at'],
            },
        ),
    ]
