# Generated by Django 5.2.8 on 2025-12-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mass', models.IntegerField(blank=True, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=100, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=100, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_year', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Starships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('cost_in_credits', models.IntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('max_atmosphering_speed', models.IntegerField(blank=True, null=True)),
                ('crew', models.IntegerField(blank=True, null=True)),
                ('passengers', models.IntegerField(blank=True, null=True)),
                ('cargo_capacity', models.IntegerField(blank=True, null=True)),
                ('consumables', models.CharField(blank=True, max_length=100, null=True)),
                ('hyperdrive_rating', models.FloatField(blank=True, null=True)),
                ('MGLT', models.IntegerField(blank=True, null=True)),
                ('starship_class', models.CharField(max_length=100)),
                ('pilots', models.ManyToManyField(blank=True, related_name='starships', to='all.author')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
